version: "3.7"
services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
            RABBITMQ_DEFAULT_VHOST: "/"
#        volumes:
#            - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
        ports:
            - 5672:5672
            - 15672:15672